# Generated by Django 5.2.1 on 2025-05-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_piscina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(default='Desconhecido', max_length=100, verbose_name='Nome Completo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('COMUM', 'Usuário Comum'), ('ADMIN', 'Administrador')], default='COMUM', max_length=5, verbose_name='Tipo'),
        ),
    ]
